int AutoBUMain();
void PrintModules(HWND hwnd);
int* retresult();
char *Info();
int* result_count();
int NPC();
int *score();
int *npcscore();
int player();
int XMax();
char *winlose();
int gift();
int ret_D3D_HWND();
void mThread();
HRESULT WINAPI Direct3DCreate9_VMTable(VOID);